### ISSUE TITLE
[BUG] Too-small input field for adjusting hotend temp

### ISSUE THREAD

**Issue by OutsourcedGuru** [Robo3D/OctoPrint-robotheme#20]
Sounds like some trouble in the main.css area (probably around the `#hotend_temp .input-mini` section).  The default for the temperature is the word "off" (lowercase) but everything's truncated except for that initial "oh" which of course looks like a zero:

![off](https://user-images.githubusercontent.com/15971213/30306374-9d3cb19a-972c-11e7-86ec-7e03d28197f5.png)

**Comment by steveruss** [comment]
@OutsourcedGuru @AllenMcAfee 

"(probably around the #hotend_temp .input-mini section)"

From what I've discovered...the problem is way higher up in the css hierarchy then the above.

It appears to be at the page bounding box level.

With the Robo theme disabled the bounding box...called div.row is 960 x 960

With the Robo theme enabled the same bounding box...(now) called div.row-fluid is 940 x 4802.

The ramifications of this decrease in the bounding box by -20 causes multiple consequences.

I've tried my best to document these consequences under issues in another repository.

Here you will find multiple visual instances of this same error as it applies to other "temperature value" fields. 
https://github.com/Robo3D/Customer_Feedback/issues/7

Here you will find another weird consequence in issue 2 of this feedback:
https://github.com/Robo3D/Customer_Feedback/issues/5

This problem even affects ALL the children of the settings menu.

With robo theme disabled:

![robothemedisabled](https://user-images.githubusercontent.com/6875909/34057541-9ccdaa22-e194-11e7-83bb-b05430acecb4.png)

With robo theme enabled:
![robothemeenabled](https://user-images.githubusercontent.com/6875909/34057564-b6b257da-e194-11e7-9a90-2536ca7a0cd7.png)


It's worth a try to set div.row-fluid to a width of 960 and see if that fixes everything.

**Comment by OutsourcedGuru** [comment]
@steveruss Excellent, I'll give that a try.

**Comment by OutsourcedGuru** [comment]
Nice try, but it looks like someone fat-fingered the `main.css` file in `~/oprint/lib/python2.7/site-packages/octoprint_robotheme/static/css`.

Actual:
```
  #hotend_temp .input-mini, #bed_temp .input-mini {
    width: 70%;
  }
```
Needed:
```
  #hotend_temp .input-mini, #bed_temp .input-mini {
    width: 70px;
  }
```

**Comment by OutsourcedGuru** [comment]
Repeat of [BUG#17](https://github.com/Robo3D/OctoPrint-robotheme/issues/17).
